cliapp:
  io:
    output-file:
  auth:
    base-uri:
    bearer-token:
  search:
    query:
    page-size: 40
  datetime:
    event-type:
    field-names:
    default-duration:
    additional-parameters:
      dummy: dummy

spring:
  main:
    web-application-type: none
