# value provided here is just to make app bootable
# see all default values in corresponding classes
cliapp:
  io:
    output-file:
  auth:
    base-uri:
    bearer-token:
  search:
    query:
    page-size: 40
  datetime:
    event-type:
    field-names:
    default-duration:
    additional-parameters:
      dummy: dummy
    zone-id:
  alarm:
    enabled: true
    period-field-name:
    is-negative-period: true
    default-duration:
    shift-based-on:
#  other-mapping:
#    list:
#      - from-field-name: Assignee
#        default-value: Unassigned
#        to-field-name: ATTENDEE

spring:
  main:
    web-application-type: none
